#pragma once

#include "ht2mp/ipc/protocol.hpp"

#include <array>
#include <cstdint>
#include <string_view>

namespace ht2mp::ipc {

enum class AuthenticationError : std::uint8_t {
  none,
  abi_mismatch,
  run_id_mismatch,
  nonce_mismatch,
  malformed_profile,
  profile_mismatch,
};

struct BridgeExpectation final {
  std::uint64_t run_id{};
  std::array<std::uint8_t, kNonceSize> nonce{};
  std::string_view profile_id;
};

// Authenticates the first bridge message against values generated by the
// sidecar. The nonce is capability-style anti-confusion for the per-run local
// pipe, not remote cryptographic authentication.
[[nodiscard]] AuthenticationError authenticate_bridge_hello(
    const BridgeHelloV1& hello,
    const BridgeExpectation& expected) noexcept;

[[nodiscard]] std::string_view to_string(AuthenticationError error) noexcept;

} // namespace ht2mp::ipc
