if(NOT DEFINED EXECUTABLE OR NOT DEFINED EXPECTED OR NOT DEFINED CLI_ARGS)
  message(FATAL_ERROR "EXECUTABLE, EXPECTED and CLI_ARGS are required")
endif()

string(REPLACE "|" ";" ARGUMENT_LIST "${CLI_ARGS}")
execute_process(
  COMMAND "${EXECUTABLE}" ${ARGUMENT_LIST}
  RESULT_VARIABLE EXIT_CODE
  OUTPUT_VARIABLE STDOUT_TEXT
  ERROR_VARIABLE STDERR_TEXT
)
if(EXIT_CODE EQUAL 0)
  message(FATAL_ERROR "CLI unexpectedly succeeded")
endif()
set(COMBINED "${STDOUT_TEXT}${STDERR_TEXT}")
string(FIND "${COMBINED}" "${EXPECTED}" MATCH_OFFSET)
if(MATCH_OFFSET EQUAL -1)
  message(FATAL_ERROR
    "CLI failed with ${EXIT_CODE}, but output did not contain '${EXPECTED}':\n${COMBINED}")
endif()
